apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
  namespace: multicluster-mgmt-argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/tommeramber/ArgoCD-GitOps-Helm-Based-Multi-Cluster-Structure.git
      revision: HEAD
      directories:
      - path: core/*
      - path: core/rbac/*
      - path: core/jobs/*
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: core 
      source:
        repoURL: https://github.com/tommeramber/ArgoCD-GitOps-Helm-Based-Multi-Cluster-Structure.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values-dev-ocp.yaml
      destination:
        server: https://kubernetes.default.svc
      syncPolicy: {}
      # Optional
      #        automated: 
      #          prune: true
      #        syncOptions:
      #        - Replace=true
