apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/tommeramber/GitOps-For-Multi-Openshift-Cluster-Management.git
      revision: HEAD
      directories:
      - path: apps/*
      - path: apps/helm-operators/*
      - path: apps/helm-operators
        exclude: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/tommeramber/GitOps-For-Multi-Openshift-Cluster-Management.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values-dev-ocp.yaml
      destination:
        server: https://kubernetes.default.svc
      syncPolicy: {}
      # Operators
      #        automated: 
      #          prune: true
      #        syncOptions:
      #        - Replace=true
