apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/tommeramber/ArgoCD-GitOps-Helm-Based-Multi-Cluster-Structure.git 
      revision: HEAD
      directories:
      - path: operators/*
      - path: operators/subs-and-customresources/*
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: operators
      source:
        repoURL: https://github.com/tommeramber/ArgoCD-GitOps-Helm-Based-Multi-Cluster-Structure.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values-dev-ocp.yaml
      destination:
        server: https://kubernetes.default.svc
      syncPolicy: {}
      # Optional
      #        automated:
      #          prune: true
      #          selfHeal: true
      #        syncOptions:
      #        - Replace=true
